language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
cache: pip
before_install:
  - pip install --upgrade pip
  - pip install wheel
  - pip install numpy scipy Cython scikit-learn matplotlib coveralls nose-cov
script:
  - nosetests --with-cov --cov=graphs/ graphs/tests/ graphs/base/tests/ graphs/construction/tests/ graphs/generators/tests/ graphs/mixins/tests/
after_success: coveralls
